name: Print Repository Sources Path

on:
  push:
    branches:
      - main

jobs:
  print_path:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Repository Sources Path
        run: |
          echo "Repository sources path: $GITHUB_WORKSPACE"
